# Generated by Django 4.1.6 on 2023-02-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('volume', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('analysis_code', models.CharField(max_length=10)),
                ('completion_date', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('consumables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base_app.consumables')),
            ],
        ),
    ]
