# Generated by Django 4.1.6 on 2023-02-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gobmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('analysis_Gcode', models.CharField(max_length=15)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TakingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_technique', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='price',
            field=models.FloatField(),
        ),
    ]
