# Generated by Django 4.1.6 on 2023-02-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0002_gobmp_takingtechnique_alter_analysis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='rater',
            field=models.ManyToManyField(to='knowledge_base_app.gobmp'),
        ),
    ]
