# Generated by Django 4.1.6 on 2023-02-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0003_analysis_rater'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='taking',
            field=models.ManyToManyField(to='knowledge_base_app.takingtechnique'),
        ),
    ]
