# Generated by Django 4.1.6 on 2023-02-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0004_analysis_taking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='taking',
        ),
    ]
