# Generated by Django 4.1.6 on 2023-02-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0005_remove_analysis_taking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='taking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base_app.takingtechnique'),
            preserve_default=False,
        ),
    ]
