# Generated by Django 4.1.6 on 2023-02-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0006_consumables_taking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='taking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base_app.takingtechnique'),
        ),
    ]
