# Generated by Django 4.1.6 on 2023-02-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0007_alter_consumables_taking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_preparation', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='how_prepare',
            field=models.ManyToManyField(to='knowledge_base_app.preparation'),
        ),
    ]
