# Generated by Django 4.1.6 on 2023-02-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0008_howtransportation_preparation_analysis_how_prepare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='how_prepare',
        ),
    ]
