# Generated by Django 4.1.6 on 2023-02-11 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0009_remove_analysis_how_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='how_prepare',
            field=models.ManyToManyField(to='knowledge_base_app.preparation'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='method_transportation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base_app.howtransportation'),
            preserve_default=False,
        ),
    ]
