# Generated by Django 4.1.6 on 2023-02-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0010_analysis_how_prepare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='how_prepare',
        ),
        migrations.AddField(
            model_name='analysis',
            name='how_prepare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base_app.preparation'),
            preserve_default=False,
        ),
    ]
