# Generated by Django 4.1.6 on 2023-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base_app', '0011_remove_analysis_how_prepare_analysis_how_prepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
